---
tittle: rOceansNew - Examples
author: I. Montero-Serra
output:
  pdf_document: default
  html_document: default
---

## rOceans 
#an R Package for exploring spatial trends in marine biodiversity and conservation

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# Functions #1 Accessing and exploring data for single / few marine species


```{r}

devtools::install_github("monteroserra/rOceansNew")
library(rOceansNew)

# Define target speices names: example with two corals
coral_species = c("Corallium rubrum", "Acropora palmata")

# Get occurrences 
corals = oceanDivDat(species_names = coral_species,
                     data_source = "OBIS_&_GBIF", 
                     remove_duplicates = T, 
                     remove_land_dots = T)

head(corals)

corals_presence = presencesRaster(occurrences=corals, 
                                         cell_size=5)

oceanMaps(corals_presence)


corals_richness = oceanRichness(occurrences=corals, 
                                cell_size=5, 
                                richness_map = T)


oceanMaps(corals_richness)


```

